name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Zip dist folder
        run: zip -r dist.zip dist
          
      - name: Upload dist to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --exclude '*' --include '*.zip'
        env:
          AWS_S3_BUCKET: rootstergg-deploy-bucket
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
      - name: Deploy to EC2 instance
        uses: appleboy/scp-action@master
        with:
          host: 3.75.194.12
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: dist.zip
          target: ~/dist.zip
        
        env:
          AWS_S3_BUCKET: rootstergg-deploy-bucket
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Unzip files
        uses: appleboy/ssh-action@master
        with:
          host: 3.75.194.12
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo unzip -o ~/dist.zip -d /var/www/rootsterxyz
          
      - name: Restart Caddy v2
        uses: appleboy/ssh-action@master
        with:
          host: 3.75.194.12
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl stop caddy
            sudo systemctl start caddy
